version: "2"

run:
  timeout: 2m
  go: "1.25"

issues:
  max-issues-per-linter: 30
  max-same-issues: 30

linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - govet
    - ineffassign
    - lll
    - misspell
    - nestif
    - noctx
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - unparam
    - unused
    - wsl_v5

  settings:
    dogsled:
      # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()).
      max-blank-identifiers: 2
    gocognit:
      # Minimal cognitive complexity to report.
      min-complexity: 20
    gocyclo:
      # Minimal cyclomatic complexity to report.
      min-complexity: 10
    govet:
      enable:
        # Report about shadowed variables.
        - shadow
    lll:
      # Minimal line length to report.
      line-length: 150
      # Tab 'length' when counting length of the line.
      tab-width: 1
    misspell:
      # Locale to use when checking for misspellings.
      locale: UK
    nestif:
      # Minimal complexity of if statements to report.
      min-complexity: 4
    prealloc:
      # Report preallocation suggestions on for loops.
      for-loops: true
      # Report preallocation suggestions on range loops.
      range-loops: true
      # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them
      simple: false
    staticcheck:
      checks:
        # Enable all checks.
        - all
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - assign-expr
        - err

  exclusions:
    # Sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      # Disable some linters for tests.
      - linters:
          - revive
          - wsl_v5
          - noctx
          - prealloc
        path: _test\.go
      # Disable reporting some particular issues.
      - linters:
          - govet
        text: declaration of "(err|ctx)" shadows declaration at
      - linters:
          - revive
        text: unless it's in another file for this package
      - linters:
          - wsl_v5
        text: invalid statement above if
      - linters:
          - wsl_v5
        text: too many lines above return
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofumpt

  settings:
    gofumpt:
      # Whether or not to use the extra rules extending gofmt.
      extra-rules: true

  exclusions:
    # Sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
